name: ScheduleShare CI
on: [push]
env:
  MONGO_CREDENTIALS: ${{ secrets.MONGO_CREDENTIALS }}
jobs:
  ScheduleShare-Test-and-Lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /backend
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: "Backend: Install modules"
        run: yarn
      - name: "Backend: Run linter"
        run: yarn lint
      - name: "Backend: Run tests"
        run: 
          echo "MONGO_CREDENTIALS:${{env.MONGO_CREDENTIALS}} > secret.env"
          yarn test
      - run: echo "ğŸ This job's status is ${{ job.status }}."